name: CI

on:
  create:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Fetch all tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Get current version
      run: echo ::set-env name=CURRENT_VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Get previous version
      run: echo ::set-env name=PREVIOUS_VERSION::$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))
    - name: Print versions
      run: |
        echo $CURRENT_VERSION
        echo $PREVIOUS_VERSION
