name: CI

on:
  create:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch history
      run: git fetch --prune --unshallow

    - name: Get current version
      run: echo ::set-env name=CURRENT_VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x

    - name: Setup env
      run: |
        echo ::set-env name=GOPATH::$(go env GOPATH)
        echo ::add-path::$(go env GOPATH)/bin

    - name: Install git-chglog
      run: go get -u github.com/git-chglog/git-chglog/cmd/git-chglog

    - name: Generate changelog
      run: git-chglog --config .github/git-chglog.yml --output CHANGELOG.md $CURRENT_VERSION

    - name: Publish docker image
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login -u russtone --password-stdin docker.pkg.github.com
        docker build -t docker.pkg.github.com/russtone/test/test:latest .
        docker push docker.pkg.github.com/russtone/test/test:latest

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
