name: CI

on:
  create:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get current version
      run: echo ::set-env name=CURRENT_VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Get previous version
      run: echo ::set-env name=PREVIOUS_VERSION::$(git describe --abbrev=0 "$CURRENT_VERSION^")
    - name: Print versions
      run: |
        echo $CURRENT_VERSION
        echo $PREVIOUS_VERSION
